### PR TITLE
Adding Node.js Auth Token Claims

### PR DESCRIPTION
**Pull request by jenperson**
Adding Admin Node.js code snippets
for https://firebase.google.com/docs/auth/admin/create-custom-tokens

### CODE REVIEW

**Comment by samtstern** [comment]
Snippets mostly look good but Travis is unhappy:

```
/home/travis/build/firebase/snippets-node/auth/create_custom_tokens.js
   3:1   error  'admin' is not defined        no-undef
   8:1   error  'admin' is not defined        no-undef
  14:11  error  Strings must use singlequote  quotes
  16:1   error  'admin' is not defined        no-undef
  21:17  error  Strings must use singlequote  quotes
  26:5   error  'uid' is already defined      no-redeclare
  26:11  error  Strings must use singlequote  quotes
  31:1   error  'admin' is not defined        no-undef
  36:17  error  Strings must use singlequote  quotes
```

**Comment by samtstern** [comment]
I think all you need is to import the Admin SDK at the top and then fix the quotes to all be `'` not `"`

**Comment by samtstern** [comment]
@jenperson Travis is wrong, not you.

**Comment by jenperson** [comment]
Alrighty. I think it's going to complain about those Firestore snippets whenever I do a PR though

**Pull request merged**
