### PR TITLE
docs(firestore): remove wrapped region tags

### PR DESCRIPTION
**Pull request by Strykrol**
Remove unused region tags now that new ones proliferated in docs.

### CODE REVIEW

**Comment by samtstern** [comment]
@Strykrol there are many internal references to these snippets, especially in the Snippet Registry. Can you remove all internal references first?

**Comment by Strykrol** [comment]
@samtstern, thank you. So I was aware they are in the registry; the registry clean-up was out-of-scope for this initial phase of firestore snippet cleanup (b/184289218). I can get in touch with @crwilcox if this is a blocking concern, but ideally we push these changes through and handle that later (presuming **nothing** is breaking of course).

Speaking to that last part, I'm trying to find an instance of one of these to-be-deleted region tags that is implemented on a devsite tenant; it's possible that some of these fell through the cracks in my CLs to swap over to the 'firestore_' prefix tags, but I'm not seeing an example. Do you have one on hand?

**Comment by samtstern** [comment]
The registry cleanup should be in scope before we delete the old tags, otherwise we'll break pages which depend on the registry.

**Comment by Strykrol** [comment]
CL is out to clean-up the registry.

**Comment by Strykrol** [comment]
@samtstern - thanks for helping move that CL along. I believe this PR is unblocked by any internal references in the registry.

**Review by samtstern — APPROVED** [review]

**Pull request merged**
