### PR TITLE
Refactoring auth snippets to ES6 + 

### PR DESCRIPTION
**Pull request by mayeedwin**
Refactoring auth snippets to ES6 + with likes of;

-  const, let

- template literals 

- arrow functions

### CODE REVIEW

**Comment by samtstern** [comment]
I'll review these PRs on Monday but I just wanted to say thank you! I think these will be a really nice improvement.

**Comment by mayeedwin** [comment]
> I'll review these PRs on Monday but I just wanted to say thank you! I think these will be a really nice improvement.

You are welcome. I will be sending in more for the other snippets

**Comment by samtstern** [comment]
@mayeedwin merged thank you!

**Comment by mayeedwin** [comment]
> @mayeedwin merged thank you!

Great. I will be sending in PRs for the rest as well.

**Pull request merged**
